[tool.ruff]
# Specify the line length
line-length = 100

# ruff only support flake8-debugger's rule T100
lint.select = ["F","T", "T100"]

# Enable or disable specific rules
#lint.select = ["E", "W", "F"]

# skipping unused errors for now: F401, F841
# skip errors due to someone elses __all__ not defined: F403
# dont error just because print is missing
lint.ignore = [ "F401", "F841", "F403", "T201", ]

# Exclude specific files or directories
exclude = [ ".git" ]

[tool.flake8]
# This is needs to be kept in sync with the ruff config
exclude = [".git",]

# ruff only support flake8-debugger's rule T100
select = ["F","T"]
# skipping unused errors for now: F401, F841
# skip errors due to someone elses __all__ not defined: F403
# dont error just because print is missing
ignore = [ "F401", "F841", "F403", "T201", ]
